apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  labels:
    app: invoice-analyzer
    component: backend
  # annotations:
  #   argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
  - secretKey: database-url
    remoteRef:
      key: invoice-analyzer/backend
      property: database-url
  - secretKey: aws-access-key-id
    remoteRef:
      key: invoice-analyzer/backend
      property: aws-access-key-id
  - secretKey: aws-secret-access-key
    remoteRef:
      key: invoice-analyzer/backend
      property: aws-secret-access-key
  - secretKey: openai-api-key
    remoteRef:
      key: invoice-analyzer/backend
      property: openai-api-key
  - secretKey: firebase-private-key
    remoteRef:
      key: invoice-analyzer/backend
      property: firebase-private-key
