apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  labels:
    app: invoice-analyzer
    component: backend
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/invoice-analyzer-backend-role
