apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  labels:
    app: invoice-analyzer
    component: backend
spec:
  selector:
    matchLabels:
      app: invoice-analyzer
      component: backend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
