apiVersion: v1
kind: Service
metadata:
  name: external-secrets-operator
  labels:
    app: external-secrets-operator
spec:
  selector:
    app: external-secrets-operator
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: webhook
    port: 443
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
