apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  labels:
    app: invoice-analyzer
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    eks.amazonaws.com/role-arn: arn:aws:iam::889039329094:role/invoice-analyzer-dev-external-secrets-sa-role
