apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secrets
  labels:
    app: invoice-analyzer
    component: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: postgres-secrets
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: invoice-analyzer/database
      property: username
  - secretKey: password
    remoteRef:
      key: invoice-analyzer/database
      property: password
