apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres
  labels:
    app: invoice-analyzer
    component: database
spec:
  selector:
    matchLabels:
      app: invoice-analyzer
      component: database
  podMetricsEndpoints:
  - port: postgres
    interval: 30s
