apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup
  labels:
    app: invoice-analyzer
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 50Gi
