apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  labels:
    app: invoice-analyzer
    component: backend
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  labels:
    app: invoice-analyzer
    component: backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend-role
subjects:
- kind: ServiceAccount
  name: backend-sa
  namespace: invoice-analyzer-dev 
