apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  labels:
    app: invoice-analyzer
    component: backend
  annotations:
    # argocd.argoproj.io/sync-wave: "1"
    eks.amazonaws.com/role-arn: arn:aws:iam::889039329094:role/invoice-analyzer-backend-sa-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  labels:
    app: invoice-analyzer
    component: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database
  labels:
    app: invoice-analyzer
    component: database
