apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  labels:
    app: invoice-analyzer
    component: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database
  labels:
    app: invoice-analyzer
    component: database
