apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: invoice-analyzer-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/invoice-analyzer-dev-backend-sa-role
