apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  labels:
    app: external-secrets-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Valescaray/gitops-repo.git
    targetRevision: main
    path: charts/external-secrets
    helm:
      values: |
        installCRDs: true
        
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::889039329094:role/invoice-analyzer-dev-external-secrets-sa-role
          name: external-secrets-operator
        
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        
        replicaCount: 1
        
        webhook:
          create: true
          port: 8081
        
        certController:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: invoice-analyzer-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
