apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd
  labels:
    app: storage
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://github.com/Valescaray/gitops-repo.git
    targetRevision: main
    path: base/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: default  # StorageClass is cluster-scoped, but we need a valid destination namespace (usually default or kube-system)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
